name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

# Add permissions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build: # Renamed from build-and-deploy for clarity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".nvmrc" # Read version from .nvmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Prepare artifact for GitHub Pages
        run: |
          mkdir ./gh-pages-artifact
          cp ./index.html ./gh-pages-artifact/
          cp -r ./dist ./gh-pages-artifact/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          # Upload the specific directory
          path: "./gh-pages-artifact"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
